### DISCUSSION TITLE
RuntimeError: CUDA error: operation not supported from ComfyUI

### DISCUSSION THREAD

**Discussion by kienerj** [mcmonkeyprojects/SwarmUI#299] [Q&A]
I'm trying to run SwarmUI on Ubuntu 22.04. after the installation went trough and trying to generate an imgae with flux (dev or schnell, same issue) I get an error:

> ComfyUI execution error: CUDA error: operation not supported
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

The installed driver from nvida is 550.54.15 with Cuda 12.4 support. 

This was right after SwarmUi launched after installation. I can use automatic1111 or fooocus just fine but these run each in their own conda environment so with SwarmUI installer I'm not all that clear were the stuff is running, do I need cuda toolkit install on OS-level or om what python environment is comfy-ui actually running?

**Comment by kienerj** [comment]
I found a solution [here](https://github.com/comfyanonymous/ComfyUI/issues/1845#issuecomment-1962677211).

The flag `--disable-cuda-malloc` needs to be passed to ComfyUI

In SwarmUI interface I was able to set this under:

Server->Backends_>ExtraArgs

and then restart the backend and the error was gone and I can generate images.
