### ISSUE TITLE
Add Official Support for NVIDIA RTX 50XX GPUs

### ISSUE THREAD

**Issue by GiorgioVitalone** [mcmonkeyprojects/SwarmUI#583]
### Feature Idea

Currently, SwarmUI does not work on the new NVIDIA RTX 50XX series GPUs. If you attempt to run SwarmUI on these cards (RTX 5090/5080) you'll encounter runtime errors around ComfyUI. The error message typically reads:

`ComfyUI execution error: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with ``TORCH_USE_CUDA_DSA`` to enable device-side assertions.`

Recent discussions and GitHub issues have highlighted that PyTorch 2.1.0 (and earlier stable releases) do not yet support compute capability sm_120. Switching to nightly builds (which support CUDA 12.8) seems to be a workaround. Incorporating this support directly in SwarmUI would eliminate the need for manual updates.

Please consider adding official support for NVIDIA RTX 50XX GPUs by updating our PyTorch dependency (or providing an alternative installation option) to include support for compute capability sm_120. 

Thank you 🙏🏻

**Comment by AmaliaKalio** [comment]
Just wanted to chime in on this, in hopes it helps anyone else who runs across the thread.

I'm on Windows and went through updating cuda/torch/torchvision/torchaudio. (Presently unclear if torchaudio was actually needed, but it kept showing up as I went down the rabbit hole.) I kept getting the same error until I finally grabbed the [suggested update for ComfyUI](https://github.com/comfyanonymous/ComfyUI/discussions/6643#discussioncomment-12518294) linked within the previously mentioned docs.

To apply, from the root of your swarm installation, go to `.\dlbackend\comfy` and copy the files in from the ComfyUI zip. (I moved everything to a new folder in `.\bak` first to be safe, but it might not be necessary.) Works like a charm.
