### ISSUE TITLE
Error while initializing backend - ComfyUI Self-Starting - will retry

### ISSUE THREAD

**Issue by celesteaeron-prog** [mcmonkeyprojects/SwarmUI#971]
### Your question

Hi. SwarmUI was running fine last night, but when I came to start it a few minutes ago I got the error in the title. I did an update, but I'm still getting it so now SwarmUI won't start at all.

### Logs

2025-08-22 10:58:19.665 [Init] === SwarmUI v0.9.6.5 Starting at 2025-08-22 10:58:19 ===
2025-08-22 10:58:19.714 [Init] Prepping extension: DerrianDistro.Extensions.KohyaDeepShrink.KohyaDeepShrink...
2025-08-22 10:58:19.717 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
2025-08-22 10:58:19.718 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2025-08-22 10:58:19.718 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2025-08-22 10:58:19.719 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2025-08-22 10:58:19.720 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2025-08-22 10:58:19.721 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2025-08-22 10:58:19.761 [Init] Parsing command line...
2025-08-22 10:58:19.763 [Init] Loading settings file...
2025-08-22 10:58:19.784 [Init] Re-saving settings file...
2025-08-22 10:58:19.809 [Init] Applying command line settings...
2025-08-22 10:58:19.820 [Init] SwarmUI was installed 2025-07-13 (40 days ago) with version 0.9.6.4
2025-08-22 10:58:19.821 [Init] Swarm base path is: D:\Download\SwarmUI
2025-08-22 10:58:19.822 [Init] Running on OS: Microsoft Windows 10.0.26100
2025-08-22 10:58:19.824 [Debug] [Load Time] Initial settings load took 0.16s (0.16s from start)
2025-08-22 10:58:19.844 [Debug] [Load Time] Extension PreInit took 0.02s (0.17s from start)
2025-08-22 10:58:19.844 [Init] Prepping options...
2025-08-22 10:58:19.867 [Init] Current git commit is [1b3162a7: swap comfy install to older stable version], marked as date 2025-08-21 01:04:15 (8 hours ago)
2025-08-22 10:58:19.932 [Init] CPU Cores: 12 | RAM: 15.24 GiB total, 8.68 GiB available, 40.88 GiB total page file, 31.28 GiB available page file
2025-08-22 10:58:19.964 [Debug] [Load Time] Prep Options took 0.11s (0.28s from start)
2025-08-22 10:58:19.964 [Debug] [Load Time] Web PreInit took 0s (0.28s from start)
2025-08-22 10:58:19.975 [Debug] [Load Time] Extensions Init took 0.02s (0.3s from start)
2025-08-22 10:58:19.976 [Debug] [Load Time] Prep Utils took 0s (0.3s from start)
2025-08-22 10:58:20.010 [Debug] [Load Time] Languages load took 0.03s (0.33s from start)
2025-08-22 10:58:20.010 [Init] Loading models list...
2025-08-22 10:58:20.051 [Debug] Have 38 Stable-Diffusion models.
2025-08-22 10:58:20.052 [Debug] Have 2 VAE models.
2025-08-22 10:58:20.082 [Debug] Have 143 LoRA models.
2025-08-22 10:58:20.094 [Debug] Have 62 Embedding models.
2025-08-22 10:58:20.094 [Debug] Have 0 ControlNet models.
2025-08-22 10:58:20.094 [Debug] Have 1 Clip models.
2025-08-22 10:58:20.095 [Debug] Have 4 ClipVision models.
2025-08-22 10:58:20.097 [Debug] [Load Time] Model listing took 0.09s (0.42s from start)
2025-08-22 10:58:20.097 [Init] Loading backends...
2025-08-22 10:58:20.099 [Init] Loading backends from file...
2025-08-22 10:58:20.102 [Debug] [Load ComfyUI Self-Starting #6] Waiting to load...
2025-08-22 10:58:20.103 [Debug] [Load Time] Backends took 0.02s (0.44s from start)
2025-08-22 10:58:20.103 [Init] Prepping API...
2025-08-22 10:58:20.104 [Debug] [Load ComfyUI Self-Starting #6] Will now load...
2025-08-22 10:58:20.104 [Init] Initializing backend #6 - ComfyUI Self-Starting...
2025-08-22 10:58:20.106 [Debug] [Load Time] API took 0s (0.44s from start)
2025-08-22 10:58:20.106 [Init] Prepping webserver...
2025-08-22 10:58:20.106 [Debug] [Load ComfyUI Self-Starting #6] Starting init...
2025-08-22 10:58:20.108 [Init] Backend request handler loop ready...
2025-08-22 10:58:20.109 [Debug] [Load ComfyUI Self-Starting #6] Will emit comfy model paths file...
2025-08-22 10:58:20.109 [Debug] [Load ComfyUI Self-Starting #6] Done emitting comfy model paths file.
2025-08-22 10:58:20.109 [Debug] [Load ComfyUI Self-Starting #6] Will add args:  --extra-model-paths-config D:\Download\SwarmUI\Data/comfy-auto-model.yaml --preview-method latent2rgb --front-end-version Comfy-Org/ComfyUI_frontend@v1.23.4
2025-08-22 10:58:20.109 [Debug] [Load ComfyUI Self-Starting #6] Will track node repo load task...
2025-08-22 10:58:20.109 [Debug] [Load ComfyUI Self-Starting #6] Will track comfy git pull auto-update task...
2025-08-22 10:58:20.109 [Debug] [Load ComfyUI Self-Starting #6] Waiting on git tasks to complete...
2025-08-22 10:58:20.110 [Debug] [Load ComfyUI Self-Starting #6] Running git pull in comfy folder...
2025-08-22 10:58:20.135 [Debug] [Load Time] [Web] WebApp builder prep took 0.03s (0.03s from start)
2025-08-22 10:58:20.162 [Debug] [Load ComfyUI Self-Starting #6] Will ensure all node repos...
2025-08-22 10:58:20.175 [Debug] [Load Time] [Web] WebApp build took 0.03s (0.06s from start)
2025-08-22 10:58:20.175 [Debug] [Load Time] [Web] exception handler took 0s (0.06s from start)
2025-08-22 10:58:20.175 [Debug] [Load Time] [Web] StartStop handler took 0s (0.06s from start)
2025-08-22 10:58:20.175 [Debug] [Load Time] [Web] static files took 0s (0.06s from start)
2025-08-22 10:58:20.226 [Debug] [Load ComfyUI Self-Starting #6] Ensure node repos - Will git pull for ComfyUI-APG_ImYourCFGNow...
2025-08-22 10:58:20.232 [Debug] [Load Time] [Web] core use calls took 0.06s (0.13s from start)
2025-08-22 10:58:20.235 [Debug] [Load Time] [Web] core maps took 0s (0.13s from start)
2025-08-22 10:58:20.235 [Init] Scan for web extensions...
2025-08-22 10:58:20.237 [Debug] [Load Time] [Web] end took 0s (0.13s from start)
2025-08-22 10:58:20.237 [Debug] [Load Time] Web prep took 0.13s (0.56s from start)
2025-08-22 10:58:20.237 [Init] Readying extensions for launch...
2025-08-22 10:58:20.238 [Debug] [Load Time] Extensions pre-launch took 0s (0.56s from start)
2025-08-22 10:58:20.238 [Init] Launching server...
2025-08-22 10:58:20.239 [Init] Starting webserver on http://localhost:7801
2025-08-22 10:58:20.280 [Debug] [Load Time] Web launch took 0.05s (0.61s from start)
2025-08-22 10:58:20.280 [Init] SwarmUI v0.9.6.5 - Local is now running.
2025-08-22 10:58:20.281 [Debug] [Load ComfyUI Self-Starting #6] Ensure node repos - Will git pull for ComfyUI_bnb_nf4_fp4_Loaders...
2025-08-22 10:58:20.335 [Debug] [Load ComfyUI Self-Starting #6] Ensure node repos - Will git pull for sd-dynamic-thresholding...
2025-08-22 10:58:20.781 [Init] Launch web browser...
2025-08-22 10:58:21.051 [Debug] [Load ComfyUI Self-Starting #6] Node pull response for ComfyUI-APG_ImYourCFGNow: Already up to date.
2025-08-22 10:58:21.089 [Debug] [Load ComfyUI Self-Starting #6] Comfy git pull response: Already up to date.
2025-08-22 10:58:21.118 [Debug] [Load ComfyUI Self-Starting #6] Node pull response for ComfyUI_bnb_nf4_fp4_Loaders: Already up to date.
2025-08-22 10:58:21.151 [Debug] [Load ComfyUI Self-Starting #6] Node pull response for sd-dynamic-thresholding: Already up to date.
2025-08-22 10:58:21.151 [Debug] [Load ComfyUI Self-Starting #6] Done ensuring all node repos.
2025-08-22 10:58:21.151 [Debug] [Load ComfyUI Self-Starting #6] All tasks done.
2025-08-22 10:58:21.154 [Debug] [Load ComfyUI Self-Starting #6] Will validate required libs...
2025-08-22 10:58:21.157 [Debug] [Load ComfyUI Self-Starting #6] Done validating required libs.
2025-08-22 10:58:21.157 [Debug] [Load ComfyUI Self-Starting #6] Starting self-start ComfyUI process...
2025-08-22 10:58:21.158 [Debug] [Load ComfyUI Self-Starting #6] Requested generic launch of dlbackend/comfy/ComfyUI/main.py on GPU 0 from ComfyUI-6
2025-08-22 10:58:21.160 [Debug] (ComfyUI-6 launch) Adding path D:\Download\SwarmUI\dlbackend\comfy\python_embeded
2025-08-22 10:58:21.160 [Debug] [Load ComfyUI Self-Starting #6] (ComfyUI-6 launch) Will use python: D:\Download\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2025-08-22 10:58:21.160 [Debug] [Load ComfyUI Self-Starting #6] Will start process...
2025-08-22 10:58:21.165 [Init] Self-Start ComfyUI-6 on port 7821 is loading...
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path checkpoints D:\Download\SwarmUI\Models\Stable-Diffusion
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path vae D:\Download\SwarmUI\Models\VAE
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path loras D:\Download\SwarmUI\Models\Lora
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path loras D:\Download\SwarmUI\Models\LyCORIS
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\ESRGAN
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\RealESRGAN
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\SwinIR
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\upscale-models
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\upscale_models
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path embeddings D:\Download\SwarmUI\Models\Embeddings
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path hypernetworks D:\Download\SwarmUI\Models\hypernetworks
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path controlnet D:\Download\SwarmUI\Models\controlnet
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path clip D:\Download\SwarmUI\Models\clip
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path clip_vision D:\Download\SwarmUI\Models\clip_vision
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path unet D:\Download\SwarmUI\Models\unet
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path diffusion_models D:\Download\SwarmUI\Models\diffusion_models
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path gligen D:\Download\SwarmUI\Models\gligen
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path ipadapter D:\Download\SwarmUI\Models\ipadapter
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path yolov8 D:\Download\SwarmUI\Models\yolov8
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path tensorrt D:\Download\SwarmUI\Models\tensorrt
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path clipseg D:\Download\SwarmUI\Models\clipseg
2025-08-22 10:58:21.349 [Debug] [ComfyUI-6/STDERR] Adding extra search path style_models D:\Download\SwarmUI\Models\style_models
2025-08-22 10:58:21.350 [Debug] [ComfyUI-6/STDERR] Adding extra search path custom_nodes D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes
2025-08-22 10:58:21.350 [Debug] [ComfyUI-6/STDERR] Adding extra search path custom_nodes D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes
2025-08-22 10:58:21.530 [Info] Creating new session 'local' for 127.0.0.1
2025-08-22 10:58:22.175 [Debug] [Load ComfyUI Self-Starting #6] Will attempt to load value set...
2025-08-22 10:58:22.641 [Debug] [ComfyUI-6/STDOUT] [START] Security scan
2025-08-22 10:58:22.641 [Debug] [ComfyUI-6/STDOUT] [DONE] Security scan
2025-08-22 10:58:22.641 [Debug] [ComfyUI-6/STDOUT] ## ComfyUI-Manager: installing dependencies done.
2025-08-22 10:58:22.642 [Debug] [ComfyUI-6/STDOUT] ** ComfyUI startup time: 2025-08-22 10:58:22.640728
2025-08-22 10:58:22.687 [Debug] [ComfyUI-6/STDOUT] ** Platform: Windows
2025-08-22 10:58:22.687 [Debug] [ComfyUI-6/STDOUT] ** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
2025-08-22 10:58:22.687 [Debug] [ComfyUI-6/STDOUT] ** Python executable: D:\Download\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2025-08-22 10:58:22.687 [Debug] [ComfyUI-6/STDOUT] ** ComfyUI Path: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI
2025-08-22 10:58:22.687 [Debug] [ComfyUI-6/STDOUT] ** Log path: D:\Download\SwarmUI\dlbackend\comfy\comfyui.log
2025-08-22 10:58:24.809 [Debug] [ComfyUI-6/STDERR] Checkpoint files will always be loaded safely.
2025-08-22 10:58:24.852 [Warning] [ComfyUI-6/STDERR] Traceback (most recent call last):
2025-08-22 10:58:24.853 [Warning] [ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 147, in <module>
2025-08-22 10:58:24.854 [Warning] [ComfyUI-6/STDERR]     import execution
2025-08-22 10:58:24.855 [Warning] [ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 15, in <module>
2025-08-22 10:58:24.857 [Warning] [ComfyUI-6/STDERR]     import comfy.model_management
2025-08-22 10:58:24.858 [Warning] [ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\comfy\model_management.py", line 236, in <module>
2025-08-22 10:58:24.858 [Warning] [ComfyUI-6/STDERR]     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
2025-08-22 10:58:24.859 [Warning] [ComfyUI-6/STDERR]                                   ^^^^^^^^^^^^^^^^^^
2025-08-22 10:58:24.859 [Warning] [ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\comfy\model_management.py", line 186, in get_torch_device
2025-08-22 10:58:24.860 [Warning] [ComfyUI-6/STDERR]     return torch.device(torch.cuda.current_device())
2025-08-22 10:58:24.861 [Warning] [ComfyUI-6/STDERR]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-08-22 10:58:24.862 [Warning] [ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
2025-08-22 10:58:24.862 [Warning] [ComfyUI-6/STDERR]     _lazy_init()
2025-08-22 10:58:24.863 [Warning] [ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
2025-08-22 10:58:24.864 [Warning] [ComfyUI-6/STDERR]     torch._C._cuda_init()
2025-08-22 10:58:24.865 [Warning] [ComfyUI-6/STDERR] RuntimeError: No CUDA GPUs are available
2025-08-22 10:58:25.412 [Info] Self-Start ComfyUI-6 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
2025-08-22 10:58:25.413 [Debug] Status of ComfyUI-6 after process end is LOADING
2025-08-22 10:58:25.413 [Info] Self-Start ComfyUI-6 had errors before shutdown:
[ComfyUI-6/STDERR] Adding extra search path checkpoints D:\Download\SwarmUI\Models\Stable-Diffusion
[ComfyUI-6/STDERR] Adding extra search path vae D:\Download\SwarmUI\Models\VAE
[ComfyUI-6/STDERR] Adding extra search path loras D:\Download\SwarmUI\Models\Lora
[ComfyUI-6/STDERR] Adding extra search path loras D:\Download\SwarmUI\Models\LyCORIS
[ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\ESRGAN
[ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\RealESRGAN
[ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\SwinIR
[ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\upscale-models
[ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\upscale_models
[ComfyUI-6/STDERR] Adding extra search path embeddings D:\Download\SwarmUI\Models\Embeddings
[ComfyUI-6/STDERR] Adding extra search path hypernetworks D:\Download\SwarmUI\Models\hypernetworks
[ComfyUI-6/STDERR] Adding extra search path controlnet D:\Download\SwarmUI\Models\controlnet
[ComfyUI-6/STDERR] Adding extra search path clip D:\Download\SwarmUI\Models\clip
[ComfyUI-6/STDERR] Adding extra search path clip_vision D:\Download\SwarmUI\Models\clip_vision
[ComfyUI-6/STDERR] Adding extra search path unet D:\Download\SwarmUI\Models\unet
[ComfyUI-6/STDERR] Adding extra search path diffusion_models D:\Download\SwarmUI\Models\diffusion_models
[ComfyUI-6/STDERR] Adding extra search path gligen D:\Download\SwarmUI\Models\gligen
[ComfyUI-6/STDERR] Adding extra search path ipadapter D:\Download\SwarmUI\Models\ipadapter
[ComfyUI-6/STDERR] Adding extra search path yolov8 D:\Download\SwarmUI\Models\yolov8
[ComfyUI-6/STDERR] Adding extra search path tensorrt D:\Download\SwarmUI\Models\tensorrt
[ComfyUI-6/STDERR] Adding extra search path clipseg D:\Download\SwarmUI\Models\clipseg
[ComfyUI-6/STDERR] Adding extra search path style_models D:\Download\SwarmUI\Models\style_models
[ComfyUI-6/STDERR] Adding extra search path custom_nodes D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes
[ComfyUI-6/STDERR] Adding extra search path custom_nodes D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes
[ComfyUI-6/STDERR] Checkpoint files will always be loaded safely.
[ComfyUI-6/STDERR] Traceback (most recent call last):
[ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\main.py", line 147, in <module>
[ComfyUI-6/STDERR]     import execution
[ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 15, in <module>
[ComfyUI-6/STDERR]     import comfy.model_management
[ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\comfy\model_management.py", line 236, in <module>
[ComfyUI-6/STDERR]     total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
[ComfyUI-6/STDERR]                                   ^^^^^^^^^^^^^^^^^^
[ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\comfy\model_management.py", line 186, in get_torch_device
[ComfyUI-6/STDERR]     return torch.device(torch.cuda.current_device())
[ComfyUI-6/STDERR]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 1026, in current_device
[ComfyUI-6/STDERR]     _lazy_init()
[ComfyUI-6/STDERR]   File "D:\Download\SwarmUI\dlbackend\comfy\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 372, in _lazy_init
[ComfyUI-6/STDERR]     torch._C._cuda_init()
[ComfyUI-6/STDERR] RuntimeError: No CUDA GPUs are available
2025-08-22 10:58:25.415 [Error] Self-Start ComfyUI-6 on port 7821 failed. AutoRestart ignored as this was an initial launch failure.
2025-08-22 10:58:26.283 [Debug] [Load ComfyUI Self-Starting #6] ComfyUI-6 self-start port 7821 loop ending (failed?)
2025-08-22 10:58:26.927 [Debug] User local requested weak refresh within 10 seconds of last refresh, ignoring as redundant.
2025-08-22 10:58:26.927 [Debug] Data refreshed!

### Other

In the log it says it can't find a 'requirements.txt' file, but as far as I'm aware there's never been such a file anyway. I always have hidden files shown and have never seen such a file in the root of my D drive.

**Comment by mcmonkey4eva** [comment]
Your error here is `No CUDA GPUs are available`
"CUDA" here just means nvidia gpu drivers essentially.

So, in other words: Your swarm install is failing to detect a valid nvidia gpu driver. Depending on why this happened, a PC restart or an nvidia driver reinstall will probably fix it.

**Comment by ghost** [comment]
That logs I pasted is actually different to the initial logs, which didn't mention not finding any GPU's, but did mention about not finding a requirements text file.

I've closed this as I'm getting different errors now, as well as multiple CMD windows opening when starting. But when I go to the logs it says it's started fine and is running, but I can't start any generations. It just hangs on 1 current generation, 1 queued.

2025-08-22 11:19:20.135 [Init] === SwarmUI v0.9.6.5 Starting at 2025-08-22 11:19:20 ===
2025-08-22 11:19:20.177 [Init] Prepping extension: DerrianDistro.Extensions.KohyaDeepShrink.KohyaDeepShrink...
2025-08-22 11:19:20.179 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
2025-08-22 11:19:20.179 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2025-08-22 11:19:20.180 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2025-08-22 11:19:20.180 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2025-08-22 11:19:20.181 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2025-08-22 11:19:20.182 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2025-08-22 11:19:20.218 [Init] Parsing command line...
2025-08-22 11:19:20.219 [Init] Loading settings file...
2025-08-22 11:19:20.239 [Init] Re-saving settings file...
2025-08-22 11:19:20.262 [Init] Applying command line settings...
2025-08-22 11:19:20.272 [Init] SwarmUI was installed 2025-07-13 (40 days ago) with version 0.9.6.4
2025-08-22 11:19:20.273 [Init] Swarm base path is: D:\Download\SwarmUI
2025-08-22 11:19:20.273 [Init] Running on OS: Microsoft Windows 10.0.26100
2025-08-22 11:19:20.274 [Debug] [Load Time] Initial settings load took 0.14s (0.14s from start)
2025-08-22 11:19:20.292 [Debug] [Load Time] Extension PreInit took 0.02s (0.16s from start)
2025-08-22 11:19:20.292 [Init] Prepping options...
2025-08-22 11:19:20.312 [Init] Current git commit is [1b3162a7: swap comfy install to older stable version], marked as date 2025-08-21 01:04:15 (9 hours ago)
2025-08-22 11:19:20.396 [Debug] [Load Time] Prep Options took 0.11s (0.27s from start)
2025-08-22 11:19:20.397 [Debug] [Load Time] Web PreInit took 0s (0.27s from start)
2025-08-22 11:19:20.408 [Debug] [Load Time] Extensions Init took 0s (0.27s from start)
2025-08-22 11:19:20.409 [Debug] [Load Time] Prep Utils took 0s (0.27s from start)
2025-08-22 11:19:20.440 [Debug] [Load Time] Languages load took 0.03s (0.3s from start)
2025-08-22 11:19:20.440 [Init] Loading models list...
2025-08-22 11:19:20.475 [Debug] Have 38 Stable-Diffusion models.
2025-08-22 11:19:20.475 [Debug] Have 2 VAE models.
2025-08-22 11:19:20.497 [Debug] Have 143 LoRA models.
2025-08-22 11:19:20.507 [Debug] Have 62 Embedding models.
2025-08-22 11:19:20.507 [Debug] Have 0 ControlNet models.
2025-08-22 11:19:20.507 [Debug] Have 1 Clip models.
2025-08-22 11:19:20.508 [Debug] Have 4 ClipVision models.
2025-08-22 11:19:20.510 [Debug] [Load Time] Model listing took 0.08s (0.38s from start)
2025-08-22 11:19:20.510 [Init] Loading backends...
2025-08-22 11:19:20.511 [Init] Loading backends from file...
2025-08-22 11:19:20.513 [Debug] [Load ComfyUI Self-Starting #6] Waiting to load...
2025-08-22 11:19:20.514 [Debug] [Load Time] Backends took 0s (0.38s from start)
2025-08-22 11:19:20.514 [Init] Prepping API...
2025-08-22 11:19:20.515 [Debug] [Load ComfyUI Self-Starting #6] Will now load...
2025-08-22 11:19:20.515 [Init] Initializing backend #6 - ComfyUI Self-Starting...
2025-08-22 11:19:20.516 [Debug] [Load ComfyUI Self-Starting #6] Starting init...
2025-08-22 11:19:20.517 [Debug] [Load Time] API took 0s (0.38s from start)
2025-08-22 11:19:20.517 [Init] Prepping webserver...
2025-08-22 11:19:20.518 [Debug] [Load ComfyUI Self-Starting #6] Will emit comfy model paths file...
2025-08-22 11:19:20.518 [Init] Backend request handler loop ready...
2025-08-22 11:19:20.519 [Debug] [Load ComfyUI Self-Starting #6] Done emitting comfy model paths file.
2025-08-22 11:19:20.519 [Debug] [Load ComfyUI Self-Starting #6] Will add args:  --extra-model-paths-config D:\Download\SwarmUI\Data/comfy-auto-model.yaml --preview-method latent2rgb --front-end-version Comfy-Org/ComfyUI_frontend@v1.23.4
2025-08-22 11:19:20.519 [Debug] [Load ComfyUI Self-Starting #6] Will track node repo load task...
2025-08-22 11:19:20.519 [Debug] [Load ComfyUI Self-Starting #6] Will track comfy git pull auto-update task...
2025-08-22 11:19:20.519 [Debug] [Load ComfyUI Self-Starting #6] Waiting on git tasks to complete...
2025-08-22 11:19:20.520 [Debug] [Load ComfyUI Self-Starting #6] Running git pull in comfy folder...
2025-08-22 11:19:20.543 [Debug] [Load Time] [Web] WebApp builder prep took 0.02s (0.02s from start)
2025-08-22 11:19:20.571 [Debug] [Load ComfyUI Self-Starting #6] Will ensure all node repos...
2025-08-22 11:19:20.581 [Debug] [Load Time] [Web] WebApp build took 0.03s (0.05s from start)
2025-08-22 11:19:20.581 [Debug] [Load Time] [Web] exception handler took 0s (0.05s from start)
2025-08-22 11:19:20.581 [Debug] [Load Time] [Web] StartStop handler took 0s (0.05s from start)
2025-08-22 11:19:20.581 [Debug] [Load Time] [Web] static files took 0s (0.05s from start)
2025-08-22 11:19:20.635 [Debug] [Load Time] [Web] core use calls took 0.06s (0.11s from start)
2025-08-22 11:19:20.636 [Debug] [Load ComfyUI Self-Starting #6] Ensure node repos - Will git pull for ComfyUI-APG_ImYourCFGNow...
2025-08-22 11:19:20.637 [Debug] [Load Time] [Web] core maps took 0s (0.11s from start)
2025-08-22 11:19:20.637 [Init] Scan for web extensions...
2025-08-22 11:19:20.639 [Debug] [Load Time] [Web] end took 0s (0.11s from start)
2025-08-22 11:19:20.639 [Debug] [Load Time] Web prep took 0.13s (0.5s from start)
2025-08-22 11:19:20.639 [Init] Readying extensions for launch...
2025-08-22 11:19:20.640 [Debug] [Load Time] Extensions pre-launch took 0s (0.5s from start)
2025-08-22 11:19:20.640 [Init] Launching server...
2025-08-22 11:19:20.642 [Init] Starting webserver on http://localhost:7801
2025-08-22 11:19:20.677 [Debug] [Load Time] Web launch took 0.03s (0.53s from start)
2025-08-22 11:19:20.699 [Debug] [Load ComfyUI Self-Starting #6] Ensure node repos - Will git pull for ComfyUI_bnb_nf4_fp4_Loaders...
2025-08-22 11:19:20.762 [Debug] [Load ComfyUI Self-Starting #6] Ensure node repos - Will git pull for sd-dynamic-thresholding...
2025-08-22 11:19:20.995 [Init] CPU Cores: 12 | RAM: 15.24 GiB total, 8.98 GiB available, 40.88 GiB total page file, 30.25 GiB available page file
2025-08-22 11:19:20.997 [Init] GPU 0: NVIDIA GeForce RTX 4050 Laptop GPU | Temp 37C | Util 0% GPU, 0% Memory | VRAM 6.00 GiB total, 5.78 GiB free, 0 B used
2025-08-22 11:19:20.998 [Init] Will use GPU accelerations specific to NVIDIA GeForce RTX 40xx series and newer.
2025-08-22 11:19:20.998 [Init] SwarmUI v0.9.6.5 - Local is now running.
2025-08-22 11:19:21.395 [Debug] [Load ComfyUI Self-Starting #6] Node pull response for ComfyUI-APG_ImYourCFGNow: Already up to date.
2025-08-22 11:19:21.417 [Debug] [Load ComfyUI Self-Starting #6] Comfy git pull response: Already up to date.
2025-08-22 11:19:21.439 [Debug] [Load ComfyUI Self-Starting #6] Node pull response for ComfyUI_bnb_nf4_fp4_Loaders: Already up to date.
2025-08-22 11:19:21.509 [Init] Launch web browser...
2025-08-22 11:19:21.579 [Debug] [Load ComfyUI Self-Starting #6] Node pull response for sd-dynamic-thresholding: Already up to date.
2025-08-22 11:19:21.579 [Debug] [Load ComfyUI Self-Starting #6] Done ensuring all node repos.
2025-08-22 11:19:21.579 [Debug] [Load ComfyUI Self-Starting #6] All tasks done.
2025-08-22 11:19:21.581 [Debug] [Load ComfyUI Self-Starting #6] Will validate required libs...
2025-08-22 11:19:21.583 [Debug] [Load ComfyUI Self-Starting #6] Done validating required libs.
2025-08-22 11:19:21.583 [Debug] [Load ComfyUI Self-Starting #6] Starting self-start ComfyUI process...
2025-08-22 11:19:21.584 [Debug] [Load ComfyUI Self-Starting #6] Requested generic launch of dlbackend/comfy/ComfyUI/main.py on GPU 0 from ComfyUI-6
2025-08-22 11:19:21.586 [Debug] (ComfyUI-6 launch) Adding path D:\Download\SwarmUI\dlbackend\comfy\python_embeded
2025-08-22 11:19:21.586 [Debug] [Load ComfyUI Self-Starting #6] (ComfyUI-6 launch) Will use python: D:\Download\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2025-08-22 11:19:21.586 [Debug] [Load ComfyUI Self-Starting #6] Will start process...
2025-08-22 11:19:21.591 [Init] Self-Start ComfyUI-6 on port 7821 is loading...
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path checkpoints D:\Download\SwarmUI\Models\Stable-Diffusion
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path vae D:\Download\SwarmUI\Models\VAE
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path loras D:\Download\SwarmUI\Models\Lora
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path loras D:\Download\SwarmUI\Models\LyCORIS
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\ESRGAN
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\RealESRGAN
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\SwinIR
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\upscale-models
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path upscale_models D:\Download\SwarmUI\Models\upscale_models
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path embeddings D:\Download\SwarmUI\Models\Embeddings
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path hypernetworks D:\Download\SwarmUI\Models\hypernetworks
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path controlnet D:\Download\SwarmUI\Models\controlnet
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path clip D:\Download\SwarmUI\Models\clip
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path clip_vision D:\Download\SwarmUI\Models\clip_vision
2025-08-22 11:19:21.756 [Debug] [ComfyUI-6/STDERR] Adding extra search path unet D:\Download\SwarmUI\Models\unet
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path diffusion_models D:\Download\SwarmUI\Models\diffusion_models
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path gligen D:\Download\SwarmUI\Models\gligen
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path ipadapter D:\Download\SwarmUI\Models\ipadapter
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path yolov8 D:\Download\SwarmUI\Models\yolov8
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path tensorrt D:\Download\SwarmUI\Models\tensorrt
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path clipseg D:\Download\SwarmUI\Models\clipseg
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path style_models D:\Download\SwarmUI\Models\style_models
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path custom_nodes D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes
2025-08-22 11:19:21.757 [Debug] [ComfyUI-6/STDERR] Adding extra search path custom_nodes D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes
2025-08-22 11:19:22.075 [Info] Creating new session 'local' for 127.0.0.1
2025-08-22 11:19:22.602 [Debug] [Load ComfyUI Self-Starting #6] Will attempt to load value set...
2025-08-22 11:19:23.058 [Debug] [ComfyUI-6/STDOUT] [START] Security scan
2025-08-22 11:19:23.058 [Debug] [ComfyUI-6/STDOUT] [DONE] Security scan
2025-08-22 11:19:23.058 [Debug] [ComfyUI-6/STDOUT] ## ComfyUI-Manager: installing dependencies done.
2025-08-22 11:19:23.058 [Debug] [ComfyUI-6/STDOUT] ** ComfyUI startup time: 2025-08-22 11:19:23.056996
2025-08-22 11:19:23.094 [Debug] [ComfyUI-6/STDOUT] ** Platform: Windows
2025-08-22 11:19:23.094 [Debug] [ComfyUI-6/STDOUT] ** Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
2025-08-22 11:19:23.094 [Debug] [ComfyUI-6/STDOUT] ** Python executable: D:\Download\SwarmUI\dlbackend\comfy\python_embeded\python.exe
2025-08-22 11:19:23.094 [Debug] [ComfyUI-6/STDOUT] ** ComfyUI Path: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI
2025-08-22 11:19:23.094 [Debug] [ComfyUI-6/STDOUT] ** Log path: D:\Download\SwarmUI\dlbackend\comfy\comfyui.log
2025-08-22 11:19:24.860 [Debug] [ComfyUI-6/STDERR] Checkpoint files will always be loaded safely.
2025-08-22 11:19:25.555 [Debug] [ComfyUI-6/STDERR] Total VRAM 6140 MB, total RAM 15609 MB
2025-08-22 11:19:25.555 [Debug] [ComfyUI-6/STDERR] pytorch version: 2.7.1+cu128
2025-08-22 11:19:25.556 [Debug] [ComfyUI-6/STDERR] Set vram state to: NORMAL_VRAM
2025-08-22 11:19:25.556 [Debug] [ComfyUI-6/STDERR] Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : cudaMallocAsync
2025-08-22 11:19:27.272 [Debug] [ComfyUI-6/STDERR] Using pytorch attention
2025-08-22 11:19:27.704 [Debug] [Load ComfyUI Self-Starting #6] Will attempt to load value set...
2025-08-22 11:19:30.091 [Debug] [ComfyUI-6/STDERR] Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]
2025-08-22 11:19:30.091 [Debug] [ComfyUI-6/STDERR] ComfyUI version: 0.3.51
2025-08-22 11:19:30.121 [Debug] [ComfyUI-6/STDERR] Using existing copy of specific frontend version tag: Comfy-Org/ComfyUI_frontend@v1.23.4
2025-08-22 11:19:30.122 [Debug] [ComfyUI-6/STDERR] [Prompt Server] web root: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.23.4
2025-08-22 11:19:31.482 [Debug] [ComfyUI-6/STDERR] ### Loading: ComfyUI-Impact-Pack (V8.19.1)
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] ----------------------------------------------------------------------------
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] [Impact Pack] The SAM2 functionality is unavailable because the `facebook/sam2` dependency is not installed.
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] Installation command:
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] D:\Download\SwarmUI\dlbackend\comfy\python_embeded\python.exe -m pip install git+https://github.com/facebookresearch/sam2
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] ----------------------------------------------------------------------------
2025-08-22 11:19:31.565 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] ----------------------------------------------------------------------------
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] [Impact Pack] The SAM2 functionality is unavailable because the `facebook/sam2` dependency is not installed.
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] Installation command:
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] D:\Download\SwarmUI\dlbackend\comfy\python_embeded\python.exe -m pip install git+https://github.com/facebookresearch/sam2
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] ----------------------------------------------------------------------------
2025-08-22 11:19:31.582 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:31.604 [Debug] [ComfyUI-6/STDERR] [Impact Pack] Wildcards loading done.
2025-08-22 11:19:31.609 [Debug] [ComfyUI-6/STDERR] ### Loading: ComfyUI-Inspire-Pack (V1.20)
2025-08-22 11:19:31.713 [Debug] [ComfyUI-6/STDOUT] ### Loading: ComfyUI-Manager (V2.50.3)
2025-08-22 11:19:31.813 [Debug] [ComfyUI-6/STDOUT] ### ComfyUI Revision: 318 [ff577936] | Released on '2025-08-22'
2025-08-22 11:19:32.498 [Debug] [ComfyUI-6/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
2025-08-22 11:19:32.573 [Debug] [ComfyUI-6/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
2025-08-22 11:19:32.585 [Debug] [ComfyUI-6/STDOUT] ------------------------------------------
2025-08-22 11:19:32.585 [Debug] [ComfyUI-6/STDOUT] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
2025-08-22 11:19:32.585 [Debug] [ComfyUI-6/STDOUT] ------------------------------------------
2025-08-22 11:19:32.585 [Debug] [ComfyUI-6/STDOUT] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
2025-08-22 11:19:32.585 [Debug] [ComfyUI-6/STDOUT] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
2025-08-22 11:19:32.585 [Debug] [ComfyUI-6/STDOUT] ------------------------------------------
2025-08-22 11:19:32.606 [Debug] [ComfyUI-6/STDOUT] [92m[tinyterraNodes] [32mLoaded[0m
2025-08-22 11:19:32.648 [Debug] [ComfyUI-6/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
2025-08-22 11:19:32.704 [Debug] [ComfyUI-6/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
2025-08-22 11:19:32.738 [Debug] [ComfyUI-6/STDOUT] [93mEfficiency Nodes Warning:[0m Failed to import python package 'simpleeval'; related nodes disabled.
2025-08-22 11:19:32.738 [Debug] [ComfyUI-6/STDOUT] 
2025-08-22 11:19:32.776 [Debug] [Load ComfyUI Self-Starting #6] Will attempt to load value set...
2025-08-22 11:19:33.197 [Debug] [ComfyUI-6/STDOUT] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
2025-08-22 11:19:33.555 [Debug] [ComfyUI-6/STDOUT] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
2025-08-22 11:19:33.555 [Debug] [ComfyUI-6/STDOUT] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
2025-08-22 11:19:33.987 [Debug] [ComfyUI-6/STDOUT] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m220[0m [32mnodes successfully.[0m
2025-08-22 11:19:33.988 [Debug] [ComfyUI-6/STDOUT] 
2025-08-22 11:19:33.988 [Debug] [ComfyUI-6/STDOUT] 	[3m[93m"Art is the lie that enables us to recognize the truth."[0m[3m - Friedrich Nietzsche[0m
2025-08-22 11:19:33.988 [Debug] [ComfyUI-6/STDOUT] 
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR] Import times for custom nodes:
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\websocket_image_save.py
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI-APG_ImYourCFGNow
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_GradientDeepShrink
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUi_PromptStylers
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\sd-dynamic-thresholding
2025-08-22 11:19:34.447 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_DiffusionModel_fp8_converter
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\images-grid-comfy-plugin
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\antrobots-comfyUI-nodepack
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyCommon
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.0 seconds: D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\ExtraNodes\SwarmComfyExtra
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.1 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.1 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.1 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.1 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.4 seconds: D:\Download\SwarmUI\src\BuiltinExtensions\ComfyUIBackend\DLNodes\ComfyUI_bnb_nf4_fp4_Loaders
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    0.8 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR]    1.2 seconds: D:\Download\SwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\was-node-suite-comfyui
2025-08-22 11:19:34.448 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:34.997 [Debug] [ComfyUI-6/STDERR] Context impl SQLiteImpl.
2025-08-22 11:19:34.997 [Debug] [ComfyUI-6/STDERR] Will assume non-transactional DDL.
2025-08-22 11:19:34.999 [Debug] [ComfyUI-6/STDERR] No target revision found.
2025-08-22 11:19:35.014 [Debug] [ComfyUI-6/STDERR] Starting server
2025-08-22 11:19:35.015 [Debug] [ComfyUI-6/STDERR] 
2025-08-22 11:19:35.015 [Debug] [ComfyUI-6/STDERR] To see the GUI go to: http://127.0.0.1:7821
2025-08-22 11:19:35.508 [Debug] [ComfyUI-6/STDERR] [Inspire Pack] IPAdapterPlus is not installed.
2025-08-22 11:19:35.776 [Debug] [Load ComfyUI Self-Starting #6] Got valid value set, will parse...
2025-08-22 11:19:35.782 [Debug] [Load ComfyUI Self-Starting #6] Done parsing value set.
2025-08-22 11:19:35.782 [Debug] [Load ComfyUI Self-Starting #6] Done! Started!
2025-08-22 11:19:35.782 [Init] Self-Start ComfyUI-6 on port 7821 started.
2025-08-22 11:19:35.784 [Debug] [Load ComfyUI Self-Starting #6] ComfyUI-6 self-start port 7821 loop ending (should now be alive)
2025-08-22 11:19:38.018 [Debug] [Load ComfyUI Self-Starting #6] Got valid value set, will parse...
2025-08-22 11:19:38.019 [Debug] [Load ComfyUI Self-Starting #6] Done parsing value set.
2025-08-22 11:19:38.027 [Debug] Have 38 Stable-Diffusion models.
2025-08-22 11:19:38.028 [Debug] Have 2 VAE models.
2025-08-22 11:19:38.046 [Debug] Have 143 LoRA models.
2025-08-22 11:19:38.054 [Debug] Have 62 Embedding models.
2025-08-22 11:19:38.054 [Debug] Have 0 ControlNet models.
2025-08-22 11:19:38.054 [Debug] Have 1 Clip models.
2025-08-22 11:19:38.055 [Debug] Have 4 ClipVision models.
2025-08-22 11:19:38.056 [Debug] Data refreshed!


2025-08-22 11:19:20.135 [Init] === SwarmUI v0.9.6.5 Starting at 2025-08-22 11:19:20 ===
2025-08-22 11:19:20.177 [Init] Prepping extension: DerrianDistro.Extensions.KohyaDeepShrink.KohyaDeepShrink...
2025-08-22 11:19:20.179 [Init] Prepping extension: SwarmUI.Builtin_ScorersExtension.ScorersExtension...
2025-08-22 11:19:20.179 [Init] Prepping extension: SwarmUI.Builtin_ImageBatchToolExtension.ImageBatchToolExtension...
2025-08-22 11:19:20.180 [Init] Prepping extension: SwarmUI.Builtin_GridGeneratorExtension.GridGeneratorExtension...
2025-08-22 11:19:20.180 [Init] Prepping extension: SwarmUI.Builtin_DynamicThresholding.DynamicThresholdingExtension...
2025-08-22 11:19:20.181 [Init] Prepping extension: SwarmUI.Builtin_ComfyUIBackend.ComfyUIBackendExtension...
2025-08-22 11:19:20.182 [Init] Prepping extension: SwarmUI.Builtin_AutoWebUIExtension.AutoWebUIBackendExtension...
2025-08-22 11:19:20.218 [Init] Parsing command line...
2025-08-22 11:19:20.219 [Init] Loading settings file...
2025-08-22 11:19:20.239 [Init] Re-saving settings file...
2025-08-22 11:19:20.262 [Init] Applying command line settings...
2025-08-22 11:19:20.272 [Init] SwarmUI was installed 2025-07-13 (40 days ago) with version 0.9.6.4
2025-08-22 11:19:20.273 [Init] Swarm base path is: D:\Download\SwarmUI
2025-08-22 11:19:20.273 [Init] Running on OS: Microsoft Windows 10.0.26100
2025-08-22 11:19:20.292 [Init] Prepping options...
2025-08-22 11:19:20.312 [Init] Current git commit is [1b3162a7: swap comfy install to older stable version], marked as date 2025-08-21 01:04:15 (9 hours ago)
2025-08-22 11:19:20.440 [Init] Loading models list...
2025-08-22 11:19:20.510 [Init] Loading backends...
2025-08-22 11:19:20.511 [Init] Loading backends from file...
2025-08-22 11:19:20.514 [Init] Prepping API...
2025-08-22 11:19:20.515 [Init] Initializing backend #6 - ComfyUI Self-Starting...
2025-08-22 11:19:20.517 [Init] Prepping webserver...
2025-08-22 11:19:20.518 [Init] Backend request handler loop ready...
2025-08-22 11:19:20.637 [Init] Scan for web extensions...
2025-08-22 11:19:20.639 [Init] Readying extensions for launch...
2025-08-22 11:19:20.640 [Init] Launching server...
2025-08-22 11:19:20.642 [Init] Starting webserver on http://localhost:7801
2025-08-22 11:19:20.995 [Init] CPU Cores: 12 | RAM: 15.24 GiB total, 8.98 GiB available, 40.88 GiB total page file, 30.25 GiB available page file
2025-08-22 11:19:20.997 [Init] GPU 0: NVIDIA GeForce RTX 4050 Laptop GPU | Temp 37C | Util 0% GPU, 0% Memory | VRAM 6.00 GiB total, 5.78 GiB free, 0 B used
2025-08-22 11:19:20.998 [Init] Will use GPU accelerations specific to NVIDIA GeForce RTX 40xx series and newer.
2025-08-22 11:19:20.998 [Init] SwarmUI v0.9.6.5 - Local is now running.
2025-08-22 11:19:21.509 [Init] Launch web browser...
2025-08-22 11:19:21.591 [Init] Self-Start ComfyUI-6 on port 7821 is loading...
2025-08-22 11:19:22.075 [Info] Creating new session 'local' for 127.0.0.1
2025-08-22 11:19:35.782 [Init] Self-Start ComfyUI-6 on port 7821 started.

**Comment by ghost** [comment]
OK, so I think I've solved it. I did download a new model last night from TensorArt and on first usage it took a lot longer to load than normal, and there was also a bit of a flicker to my screen when loading, but because the model seemed to run okay I thought nothing of it. But I've just moved that model to the recycle bin and tried SwarmUI again and it loaded fine this time. So I assume something is up with that model. It is a reprint from CivitAI. I downloaded it from TA as I can no longer use CivitAI because UK users are now blocked.
